eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defauleZone: http://localhost:8761/euraka/
  instance:
    hostname: localhost

message: "Global logic"
